### ISSUE TITLE
Parse 2012 General Election Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-mt#3]
Montana has an online reporting system similar to Oregon's, for which [we have a Python parser](https://github.com/openelections/openelections-data-or/blob/master/src/parsers/sos_parser.py). Adapt the parser to pull in JSON feeds for the [2012 general election](http://mtelectionresults.gov/Default.aspx?eid=4), including federal, statewide and state legislative (Senate and House) contests.

The resulting CSV file should be named `20121106__mt__general__precinct.csv` and have the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

**Comment by tamilyn** [comment]
It will be a few days before I can get to it, but if no one else is interested, I can do this.

**Comment by dwillis** [comment]
@tamilyn That would be awesome, thank you! btw, I managed to parse most of Arkansas' 2012 general using your fork of Clarify!

**Comment by GPHemsley** [comment]
The individual pages have an export link in the upper right corner, though it exports as an Excel file (but at least it's XLSX). That should make it easier, no?

(Does it matter that they're marked as unofficial results?)

**Comment by GPHemsley** [comment]
Actually, it looks like you can get all the data in one export:

http://mtelectionresults.gov/ResultsExport.aspx?eid=4

**Comment by GPHemsley** [comment]
http://mtresultswebservices.usgovcloudapp.net/ResultsAjax.svc?wsdl=wsdl0 lists endpoints you can hit to get JSON data back.
